name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install llvm clang libboost-all-dev libgtest-dev

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build . --target llang

    - name: Test
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build . --target test

    - name: Style
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build . --target lint
